### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by Abbondanzo** [Abbondanzo/noodles#9]
## Motivation
I realized I am easily distracted by life, so I want to use this issue to write down a stream of consciousness; for all the things left to do before I can consider this site "released". 

## Shit to do
- [x] Global Partials & Pages
  - [x] Add a footer section with the following links
    - [x] Sitemap #14
    - [x] Terms & Conditions #14
    - [x] Privacy Policy #14
    - [x] DMCA (hah) #14 4c4356e94445f034a06f2eec08461771aa903d41
    - [x] FAQ #14 4c4356e94445f034a06f2eec08461771aa903d41
    - [x] Contact support (GH issues) #14 4c4356e94445f034a06f2eec08461771aa903d41
    - [x] Feedback (GH issues) #14 4c4356e94445f034a06f2eec08461771aa903d41
    - [x] Parental Controls #14 4c4356e94445f034a06f2eec08461771aa903d41
- [x] Content Generators
  - [x] Comments + Users #15 
  - [x] ~Brand photos~
- [x] Pages
  - [x] Categories (all) #10
  - [x] Category (specific) #10
  - [x] Brands (all) #11
  - [x] Brand (specific) #11 #13
  - [x] ~Live Cams (just a whole bunch of random entries, honestly might delete this one)~
  - [x] Community
    - [x] Comment feed #15 
  - [x] ~Photos (just link to full-size downloads)~
- [x] Stupid features
  - [x] OG:Image and meta descriptions ec2b26cdba8f3e9b7937f7782fe28573c32de718
  - [x] Mobile support 
    - [x] [CSS only menu](https://alvarotrigo.com/blog/hamburger-menu-css/), no JavaScript #19 
    - [x] Grid collapsing #19 
  - [x] Upload button
    - [x] Link out to a PR template for starters #17
    - [x] ~(Stretch) hook up to a shitty serverless function that allows photo uploads and turns them into PRs. Again, could be a fucked idea~
  - [x] Hooking up `.pseudo-interactive` with a simple script that displays a modal #20 
  - [x] Visually Impaired mode ([⠠⠊ ⠓⠁⠧⠑ ⠎⠕ ⠍⠁⠝⠽ ⠊⠙⠑⠁⠎](https://www.byronknoll.com/braille2.html?text=I+have+so+many+ideas)) #18 
  - [x] [Upgrade to premium](https://www.loveandlemons.com/homemade-pasta-recipe/) #17
  - [x] [Shop](https://www.wholefoodsmarket.com/search?text=Pasta) button #17

**Comment by Abbondanzo** [comment]
Aaaaaaaand that's a wrap. Struck through some of the ideas which were too involved and/or didn't make much sense in the context of this website. Cutting a release for this project now
